import { useMemo, useState } from 'react';
import { AnimatePresence } from 'framer-motion';
import { BookOpen, Calendar, Check, Clock, HelpCircle, Link, Search, Share2, Shield, User, X } from 'lucide-react';
import ModalShell from './ModalShell';

export default function BlogGuideSheet({ selectedBlog, onClose, onSafeTalk }) {
  const [tab, setTab] = useState('blog');
  const [searchQuery, setSearchQuery] = useState('');
  const [copied, setCopied] = useState(false);
  const filteredFaqs = useMemo(() => selectedBlog ? selectedBlog.faqs.filter(f => f.question.toLowerCase().includes(searchQuery.toLowerCase()) || f.answer.toLowerCase().includes(searchQuery.toLowerCase())) : [], [selectedBlog, searchQuery]);
  const copyLink = async () => { await navigator.clipboard?.writeText(`${location.origin}${location.pathname}?guide=${selectedBlog?.id || ''}`); setCopied(true); setTimeout(() => setCopied(false), 1500); };
  const shareArticle = async () => navigator.share ? navigator.share({ title: selectedBlog?.blog?.title || selectedBlog?.title, text: selectedBlog?.desc, url: `${location.origin}${location.pathname}?guide=${selectedBlog?.id}` }) : copyLink();

  return <AnimatePresence>{selectedBlog && <ModalShell onClose={onClose} maxWidth="md:max-w-3xl" title={selectedBlog.title} subtitle={`${selectedBlog.meta} · Premium Security Advisory`}>
    <div className="flex flex-wrap items-center justify-between gap-2 mb-3 bg-[#F5F3EF]/60 border border-[#D9D6D1]/30 p-2 rounded-xl shrink-0 font-sans"><div className="flex items-center gap-1.5"><button onClick={copyLink} className="flex items-center gap-1 px-2.5 py-1.5 bg-white border border-[#D9D6D1]/60 text-[#016970] text-[11.5px] font-bold rounded-lg">{copied ? <><Check size={11}/>Link Copied</> : <><Link size={11}/>Copy Link</>}</button><button onClick={shareArticle} className="flex items-center gap-1 px-2.5 py-1.5 bg-[#016970] text-white text-[11.5px] font-bold rounded-lg"><Share2 size={11}/>Share Article</button></div></div>
    <div className="flex bg-[#F5F3EF] p-1 rounded-xl mb-4 shrink-0 font-sans border border-[#D9D6D1]/45"><Tab active={tab==='blog'} onClick={() => { setTab('blog'); setSearchQuery(''); }} icon={<BookOpen size={13}/>} label="Read Advisory Blog"/><Tab active={tab==='faqs'} onClick={() => setTab('faqs')} icon={<HelpCircle size={13}/>} label="Search Q&A FAQs"/></div>
    <p className="text-[12.5px] text-[#6E6B67] italic leading-relaxed mb-4 shrink-0 font-sans">"{selectedBlog.introduction}"</p>
    <div className="flex-1 overflow-y-auto pr-0.5 scrollbar-none pb-4 text-left space-y-4">
      {tab === 'blog' ? <div className="space-y-5"><div className="flex items-center gap-2.5 bg-[#F5F3EF]/65 p-3 rounded-xl border border-[#D9D6D1]/30"><div className="w-8 h-8 rounded-full bg-[#016970]/15 flex items-center justify-center text-[#016970]"><User size={13}/></div><div className="flex-1 min-w-0"><p className="text-[12px] font-bold text-[#1A1815] truncate">{selectedBlog.blog.author}</p><div className="flex items-center gap-1.5 text-[10px] text-[#6E6B67] mt-0.5"><span className="flex items-center gap-0.5"><Calendar size={10}/>{selectedBlog.blog.publishedDate}</span><span>•</span><span className="flex items-center gap-0.5"><Clock size={10}/>{selectedBlog.blog.readTime}</span></div></div></div><h4 className="font-serif text-[18px] leading-snug text-[#1A1815] font-semibold">{selectedBlog.blog.title}</h4>{selectedBlog.blog.sections.map((section) => <div key={section.heading} className="space-y-1.5"><h5 className="font-serif text-[14px] font-semibold text-[#016970]">▲ {section.heading}</h5>{section.paragraphs.map((p, i) => <p key={i} className="text-[12.5px] text-[#6E6B67] leading-relaxed font-sans">{p}</p>)}</div>)}<div className="p-4 bg-[#F5F3EF] rounded-xl border border-[#D9D6D1]/45 space-y-2.5"><h5 className="text-[11px] font-bold uppercase tracking-widest text-[#1A1815] flex items-center gap-1.5"><Shield size={12} className="text-[#016970]"/>Core Safeguard Takeaways</h5><ul className="space-y-2">{selectedBlog.blog.keyTakeaways.map((t) => <li key={t} className="flex gap-2 items-start text-[12px] text-[#6E6B67] leading-relaxed"><Check size={14} className="text-[#016970] shrink-0 mt-0.5"/>{t}</li>)}</ul></div></div> : <div className="space-y-4"><div className="relative"><Search size={14} className="absolute left-3 top-3 text-[#6E6B67]"/><input value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)} placeholder="Search questions on this topic..." className="w-full h-10 pl-9 pr-8 rounded-lg bg-[#F5F3EF] border border-[#D9D6D1]/55 text-[13px]" />{searchQuery && <button onClick={() => setSearchQuery('')} className="absolute right-2 top-3"><X size={14}/></button>}</div>{filteredFaqs.map((faq) => <div key={faq.question} className="p-3.5 rounded-xl bg-[#F5F3EF] border border-[#D9D6D1]/30"><h5 className="font-serif text-[14px] text-[#1A1815] font-semibold leading-snug"><span className="text-[#016970] font-bold">Q. </span>{faq.question}</h5><p className="text-[12px] text-[#6E6B67] leading-relaxed mt-2 pl-4 border-l border-[#016970]/15">{faq.answer}</p></div>)}</div>}
      <div className="p-4 bg-[#016970] rounded-xl text-white text-center"><p className="font-serif text-[15px] mb-2">Need private help for this topic?</p><button onClick={() => { onClose(); setTimeout(() => onSafeTalk(selectedBlog.title), 150); }} className="w-full py-2.5 bg-white text-[#016970] text-[13px] font-bold rounded-lg">Talk Confidentially</button></div>
    </div>
  </ModalShell>}</AnimatePresence>;
}
function Tab({ active, onClick, icon, label }) { return <button onClick={onClick} className={`flex-1 py-2 text-[12px] font-bold rounded-lg transition-all flex items-center justify-center gap-1.5 ${active ? 'bg-white text-[#016970] shadow-xs' : 'text-[#6E6B67]'}`}>{icon}<span>{label}</span></button>; }
