import { motion, AnimatePresence } from 'framer-motion';
const faqs = [
  ['Is the consultation confidential?', 'Yes. All discussions, documents, and personal details shared during the consultation are handled privately and with discretion.'],
  ['Can I consult before taking any legal action?', 'Yes. Many people seek guidance before filing, responding, or making decisions during matrimonial or family disputes.'],
  ['Do I need to visit physically for the consultation?', 'No. Consultations can be scheduled online through phone or video calls.'],
  ['What should I do if I receive a legal notice or threat?', 'Avoid reacting emotionally or responding immediately without guidance.'],
  ['Can family disputes be resolved without going to court?', 'In many situations, disputes can be addressed through discussion, mediation, or settlement efforts.'],
  ['What happens during the first consultation?', 'The first session focuses on understanding your situation, concerns, and available options.'],
];
export default function FAQSection({ openFaq, setOpenFaq }) { return <section id="faqs" className="w-full py-16 bg-[#FBFAF8] border-t border-[#D9D6D1]/40 px-4"><div className="max-w-3xl mx-auto text-center mb-12"><span className="text-[11px] font-bold uppercase tracking-widest text-[#016970]">FAQ</span><h2 className="font-serif text-[28px] md:text-[34px] text-[#1A1815] mt-2 leading-tight">Common Questions</h2><p className="text-[#6E6B67] text-[14px] md:text-[15px] leading-relaxed mt-3 max-w-md mx-auto">Answers to standard things people ask us about their safety and privacy.</p></div><div className="max-w-5xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-4">{faqs.map(([q, a], index) => { const isOpen = openFaq === index; return <div key={q} className="border border-[#D9D6D1]/40 rounded-xl bg-[#F5F3EF] overflow-hidden"><button onClick={() => setOpenFaq(isOpen ? null : index)} className="w-full text-left p-4 flex justify-between items-center gap-4 cursor-pointer"><span className="font-serif text-[14px] text-[#1A1815] leading-snug">{q}</span><span className={`text-[12px] text-[#016970] font-bold transition-transform duration-200 shrink-0 ${isOpen ? 'rotate-45' : ''}`}>＋</span></button><AnimatePresence initial={false}>{isOpen && <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }}><div className="px-4 pb-4 pt-1 border-t border-[#D9D6D1]/20 text-[13px] text-[#6E6B67] leading-relaxed font-sans">{a}</div></motion.div>}</AnimatePresence></div>; })}</div></section>; }
